/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {StyleSheet, Text, View} from 'react-native';
import RNReactNativeGemius from 'react-native-gemius';

export default class App extends Component<{}> {
  state = {
    status: 'starting',
    message: '--',
  };
  componentDidMount() {
    try {
      RNReactNativeGemius.sampleMethod('Testing', 456, (message) => {
        this.setState({
          status: 'Native callback received',
          message,
        });
      });
    } catch (error) {
      console.log('TRACKING::GEMIUS::sampleMethod failed: ', error);
    }
    try {
      RNReactNativeGemius.setAppInfo('atHome.lu', '0.0.3');
      RNReactNativeGemius.setGemiusInfo(
        'https://galu.hit.gemius.pl',
        'bPblRse1ibFjlJsGSvqLIpbBDfZI3xtEqedoSGJIaBb.E7',
        'bPblRse1ibFjlJsGSvqLIpbBDfZI3xtEqedoSGJIaBb.E7',
      );
      console.log('TRACKING::GEMIUS::VieWed page: ', 'example screen');
      RNReactNativeGemius.sendPageViewedEvent();
    } catch (error) {
      console.log('TRACKING::GEMIUS::configuration failed: ', error);
    }
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆RNReactNativeGemius example☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
        <Text style={styles.instructions}>{this.state.message}</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
